### ISSUE TITLE
stopped working a couple of days ago

### ISSUE THREAD

**Issue by 3DLW81BJwK** [RamKromberg/mangoripper#1]
batoto never really worked for me. Now mangastream stopped working.

Thanks

**Comment by RamKromberg** [comment]
A user? That's a pleasant surprise :)

I'll brush up on my Go and look into it in the next couple of days.

If you find any other problems, don't shy away from reporting them as soon as possible. With zdude falling off the earth and everything, testing and bug submissions are up to the users :)

**Comment by RamKromberg** [comment]
All done. Also hardcoded some delays since servers became unresponsive with multiple consecutive downloads.

There's still no queue or automatic retries so it's still light, easy to maintain and non-intrusive.
